// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo4J0WXYtCJgs1hnFs2S6Dtz8V_3T-zLI',
    appId: '1:40882805489:web:7a25c38cd804d52d0f6750',
    messagingSenderId: '40882805489',
    projectId: 'fir-task-manager-app-b6564',
    authDomain: 'fir-task-manager-app-b6564.firebaseapp.com',
    storageBucket: 'fir-task-manager-app-b6564.firebasestorage.app',
    measurementId: 'G-83FNFJJ841',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOmYtEsDqBXmerCOSfgMEjmzOHTynRzX8',
    appId: '1:40882805489:android:4a3ee6dc4f666d4d0f6750',
    messagingSenderId: '40882805489',
    projectId: 'fir-task-manager-app-b6564',
    storageBucket: 'fir-task-manager-app-b6564.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_EFfjyPaewiCr5JHeuTohq_o1BdnZqq8',
    appId: '1:40882805489:ios:1611b0acaff0986c0f6750',
    messagingSenderId: '40882805489',
    projectId: 'fir-task-manager-app-b6564',
    storageBucket: 'fir-task-manager-app-b6564.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTaskManager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_EFfjyPaewiCr5JHeuTohq_o1BdnZqq8',
    appId: '1:40882805489:ios:1611b0acaff0986c0f6750',
    messagingSenderId: '40882805489',
    projectId: 'fir-task-manager-app-b6564',
    storageBucket: 'fir-task-manager-app-b6564.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo4J0WXYtCJgs1hnFs2S6Dtz8V_3T-zLI',
    appId: '1:40882805489:web:8f929ebb40c43f1c0f6750',
    messagingSenderId: '40882805489',
    projectId: 'fir-task-manager-app-b6564',
    authDomain: 'fir-task-manager-app-b6564.firebaseapp.com',
    storageBucket: 'fir-task-manager-app-b6564.firebasestorage.app',
    measurementId: 'G-1BPRVNHZ3E',
  );
}
